services:
  java_app_apc: 
    container_name: java_app_apc
    image: ivansanmartin/pdes-2024-apc-backend:1.1.0
    environment: 
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD} 
      - ML_TOKEN=${ML_TOKEN}
    ports:
      - '8080:8080'
    expose:
      - '8080'
    depends_on:
      - apc_db
    build: . 

  apc_db:
    container_name: apc_db
    image: postgres:14.13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=apc_dev
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - apc_db:/var/lib/postgresql/data
volumes:
  apc_db:
    driver: local