services:
  java_app_apc: 
    container_name: java_app_apc
    image: ivansanmartin/pdes-2024-apc-backend:latest
    environment: 
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD} 
      - ML_TOKEN=${ML_TOKEN}
    ports:
      - '8080:8080'
    expose:
      - '8080'
    depends_on:
      - apc_db
    build: . 

  react_app_apc:
    container_name: react_app_apc
    image: ivansanmartin/pdes-2024-apc-frontend:latest
    ports:
      - '3000:3000'
    expose: 
      - '3000'
    depends_on:
      - java_app_apc

  apc_db:
    container_name: apc_db
    image: postgres:14.13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=apc_dev
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - apc_db:/var/lib/postgresql/data
  k6:
    image: grafana/k6:latest
    network_mode: host
    volumes: 
      - ./k6/src:/src

volumes:
  apc_db:
    driver: local