#
# Build stage
#
FROM gradle:jdk17-jammy AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle init --overwrite
RUN gradle build 

#
# Package stage
#
FROM openjdk:17-jdk-alpine
COPY --from=build /home/gradle/src/build/libs/*.war apc-java-app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "apc-java-app.jar"] 