services:
  apc_db:
    container_name: apc_db
    image: postgres:14.13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=apc_dev
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - apc_db:/var/lib/postgresql/data
volumes:
  apc_db:
    driver: local